line-length = 100
target-version = "py311"

exclude = [".git", ".venv", "__pycache__", "build", "dist"]

[lint]
select = ["E", "F", "I", "W"]
ignore = ["E201", "E202", "E501"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
